<a href="https://colab.research.google.com/github/MrCepesh/Innopolis/blob/main/NumPy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Упражнения с NumPy 

Давайте проверим ваши знания. Мы начнем с нескольких простых задач, а затем вам будут заданы несколько более сложных вопросов.

Важно! Код, который вы напишите в этом ноутбуке, вам нужно сохранить в виде файла c именем "Numpy_solutions.ipynb" в вашем личном репозитории на GitHub.

#### 1. Импорт NumPy 

In [27]:
import numpy as np

#### 2. Создать массив из 10 нулей

In [28]:
np.zeros(10) # Ваш код


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# не пишите код в этой ячейке

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Создать массив из 10 единиц

In [29]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# не пишите код в этой ячейке

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Создать массив из  10 пятерок

In [32]:
np.repeat(5.,10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# не пишите код в этой ячейке

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Создать массив из целых чисел от 10 до 50

In [33]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# не пишите код в этой ячейке

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Создать массив из четных числел от 10 до 50

In [34]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# не пишите код в этой ячейке

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Создать матрицу 3х3 с числами от 0 до 8

In [35]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# не пишите код в этой ячейке

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Создать единичную матрицу 3x3 

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# не пишите код в этой ячейке

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Используйте NumPy для генерации случайного числа от 0 до 1
<br>ПРИМЕЧАНИЕ. Значение вашего результата должно отличаться от приведенного ниже.

In [41]:
np.random.rand(1,1)

array([[0.45149982]])

In [ ]:
# не пишите код в этой ячейке

array([0.65248055])

#### Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения
<br>ПРИМЕЧАНИЕ. Значение вашего результата должно отличаться от приведенного ниже.

In [50]:
np.random.normal(size=25)

array([-0.71310054,  1.5868659 ,  0.78557973,  0.48706878, -0.01347501,
       -2.00327736,  0.6721659 ,  0.36854266,  0.08425714,  0.43915249,
        1.28505134,  1.50398718, -0.84062634,  0.20726692,  1.44932441,
       -0.85680419,  0.60370862, -0.35233779, -0.68150428, -0.11351495,
       -0.56796433,  0.0795974 , -0.43004712, -0.86237477, -0.27704158])

In [ ]:
# не пишите код в этой ячейке

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Создайте следующую матрицу:

In [53]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# не пишите код в этой ячейке

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Создайте массив из 20 линейно расположенных точек между 0 и 1:

In [54]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# не пишите код в этой ячейке

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy индексация и выборка

Дана стартовая матрица (обязательно запустите ячейку ниже!). Вам необходимо повторить выходные результаты матрицы:

In [55]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Напишите код, который воспроизводит вывод, показанный ниже.


In [57]:
# CODE HERE
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# не пишите код в этой ячейке

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Напишите код, который воспроизводит вывод, показанный ниже.

In [58]:
mat[3,4]

20

In [ ]:
# не пишите код в этой ячейке

20

#### 15. Напишите код, который воспроизводит вывод, показанный ниже.

In [61]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# не пишите код в этой ячейке

array([[ 2],
       [ 7],
       [12]])

#### 16. Напишите код, который воспроизводит вывод, показанный ниже.

In [62]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
# не пишите код в этой ячейке

array([21, 22, 23, 24, 25])

#### 17. Напишите код, который воспроизводит вывод, показанный ниже.

In [64]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# не пишите код в этой ячейке

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Операции NumPy 

#### 18. Получить сумму всех значений в матрице mat

In [67]:
mat.sum()

325

In [ ]:
# не пишите код в этой ячейке

325

#### 19. Получить стандартное отклонение в матрице mat

In [68]:
mat.std()

7.211102550927978

In [ ]:
# не пишите код в этой ячейке

7.211102550927978

#### 20. Получить сумму значений в колонках в матрице mat

In [70]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# не пишите код в этой ячейке

array([55, 60, 65, 70, 75])

## Бонусный вопрос

Есть ли способ гарантировать, что мы всегда получим одинаковые случайные числа?

In [76]:
np.random.seed(2)
np.random.randint(1,100)

41